### PR TITLE
Added support for server-side auth

### PR DESCRIPTION
**Pull request by vascofg**
As discussed in #4, I've found a solution for automatically authenticating users.
In my case I have my own authentication scheme for a back-office application where I want to show analytics and it doesn't make sense to have the user authenticating twice.
I've found this [example](https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/) which explains this mechanism in detail.

### CODE REVIEW

**Comment by revolunet** [comment]
That's a very cool contribution, thanks a lot !

Could we only use `props.accesToken`  ?

If `accesToken` is given, then use it, otherwise, use `clientId` ?

**Comment by vascofg** [comment]
I thought about it, only problem is if someone defines both props.
It's up to you, either way is fine by me.

**Comment by revolunet** [comment]
I'm not sure but if `accesToken` is given then we should use this one first ?

With a good README we can make this crystal clear ?

**Comment by vascofg** [comment]
I've updated the code and docs, what do you think?

**Comment by revolunet** [comment]
that's pretty awesome, thank you !

**Comment by revolunet** [comment]
thanks ! publish as 1.2.0 !

**Pull request merged**
